name:DRr Dream

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 
      run: echo Hello, world!
    - name:
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
